name: Linear - PR Approved

on:
  pull_request_review:
    types:
      - submitted

jobs:
  move-to-ready-staging:
    if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Move issue to Ready To Test On Staging
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          TARGET_STATE_ID: ${{ secrets.LINEAR_STATE_READY_TO_TEST_ON_STAGING_ID }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: node scripts/linear/moveIssue.js
